# Generated by Django 4.2.2 on 2025-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FCCLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fcc_location_id", models.BigIntegerField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("state_name", models.CharField(max_length=100)),
                ("county_name", models.CharField(max_length=100)),
                ("state_geoid", models.BigIntegerField()),
                ("county_geoid", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fcc_bdc_rel6",
                "ordering": ["state_name"],
            },
        ),
    ]
