# Generated by Django 4.2.2 on 2025-06-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcc_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fcclocations",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fcclocations",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="fcclocations",
            name="county_geoid",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="fcclocations",
            name="county_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="fcclocations",
            name="state_geoid",
            field=models.BigIntegerField(null=True),
        ),
    ]
