# Generated by Django 5.1.7 on 2025-03-24 16:43

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_style', models.JSONField(default=dict)),
                ('icon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_options', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'layer_types_wiroi_online',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_visible_by_default', models.BooleanField(default=True)),
                ('is_expanded_by_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='projects.project')),
            ],
            options={
                'db_table': 'project_layer_groups_wiroi_online',
                'ordering': ['project', 'display_order'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('z_index', models.IntegerField(default=0)),
                ('is_visible_by_default', models.BooleanField(default=True)),
                ('min_zoom_visibility', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)])),
                ('max_zoom_visibility', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)])),
                ('marker_type', models.CharField(blank=True, max_length=50, null=True)),
                ('marker_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('marker_options', models.JSONField(blank=True, default=dict)),
                ('enable_clustering', models.BooleanField(default=False)),
                ('clustering_options', models.JSONField(blank=True, default=dict)),
                ('enable_labels', models.BooleanField(default=False)),
                ('label_options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_count', models.IntegerField(default=0)),
                ('last_data_update', models.DateTimeField(blank=True, null=True)),
                ('layer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='layers.layertype')),
                ('project_layer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='layers.projectlayergroup')),
            ],
            options={
                'db_table': 'project_layers_wiroi_online',
                'ordering': ['project_layer_group', 'z_index'],
                'unique_together': {('project_layer_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LayerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_permissions', to='clients.clientproject')),
                ('project_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='layers.projectlayer')),
            ],
            options={
                'db_table': 'layer_permissions_wiroi_online',
                'unique_together': {('project_layer', 'client_project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField(default=dict)),
                ('feature_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('project_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='layers.projectlayer')),
            ],
            options={
                'db_table': 'project_layer_data_wiroi_online',
                'indexes': [models.Index(fields=['project_layer', 'feature_id'], name='project_lay_project_1a35e7_idx'), models.Index(fields=['project_layer', 'created_at'], name='project_lay_project_7d2947_idx')],
            },
        ),
    ]
