# Generated by Django 5.1.7 on 2025-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlayer',
            name='marker_library_name',
            field=models.CharField(blank=True, help_text='Temporary field until styling app is implemented', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectlayer',
            name='popup_template_name',
            field=models.CharField(blank=True, help_text='Temporary field until styling app is implemented', max_length=255, null=True),
        ),
    ]
