# Generated by Django 5.1.7 on 2025-03-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_projectlayer_marker_library_name_and_more'),
        ('styling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlayer',
            name='marker_library_name',
        ),
        migrations.RemoveField(
            model_name='projectlayer',
            name='popup_template_name',
        ),
        migrations.AddField(
            model_name='projectlayer',
            name='marker_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='styling.markerlibrary'),
        ),
        migrations.AddField(
            model_name='projectlayer',
            name='popup_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='styling.popuptemplate'),
        ),
    ]
