# Generated by Django 5.1.7 on 2025-03-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_remove_projectlayer_marker_library_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlayer',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this layer is visible to unauthenticated users via shared links'),
        ),
    ]
