# Generated by Django 5.1.7 on 2025-06-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_projectlayer_original_crs_projectlayer_target_crs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBRSLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_fips', models.CharField(db_index=True, max_length=2)),
                ('county_fips', models.CharField(db_index=True, max_length=3)),
                ('county_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=10)),
                ('bidder', models.CharField(max_length=200)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('frequency_mhz', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbrs_licenses',
                'indexes': [models.Index(fields=['state_fips', 'county_fips'], name='cbrs_licens_state_f_4a8266_idx')],
                'unique_together': {('state_fips', 'county_fips', 'channel', 'bidder')},
            },
        ),
    ]
