# Generated by Django 5.1.7 on 2025-06-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_cbrslicense'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cbrslicense',
            name='cbrs_licens_state_f_4a8266_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cbrslicense',
            unique_together={('state_abbr', 'county_fips', 'channel', 'bidder')},
        ),
        migrations.AddField(
            model_name='cbrslicense',
            name='state_abbr',
            field=models.CharField(db_index=True, default='OH', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cbrslicense',
            name='county_fips',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AddIndex(
            model_name='cbrslicense',
            index=models.Index(fields=['state_abbr', 'county_fips'], name='cbrs_licens_state_a_a781c5_idx'),
        ),
        migrations.RemoveField(
            model_name='cbrslicense',
            name='state_fips',
        ),
        migrations.RemoveField(
            model_name='cbrslicense',
            name='state_name',
        ),
    ]
