# Generated by Django 5.1.7 on 2025-03-24 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('default_center_lat', models.FloatField(default=0)),
                ('default_center_lng', models.FloatField(default=0)),
                ('default_zoom_level', models.IntegerField(default=5)),
                ('map_controls', models.JSONField(blank=True, default=dict)),
                ('map_options', models.JSONField(blank=True, default=dict)),
                ('max_zoom', models.IntegerField(default=18)),
                ('min_zoom', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_wiroi_online',
                'ordering': ['-created_at'],
            },
        ),
    ]
