# Generated by Django 5.1.7 on 2025-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state_abbr',
            field=models.CharField(default='OH', max_length=2),
            preserve_default=False,
        ),
    ]
