# Generated by Django 4.2.2 on 2025-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FCCLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fcc_location_id", models.BigIntegerField()),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("state_name", models.CharField(max_length=100)),
                ("county_geoid", models.BigIntegerField()),
            ],
            options={
                "db_table": "fcc_rel6",
            },
        ),
    ]
