# Generated by Django 4.2.2 on 2025-06-23 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fcc_bdc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcclocations",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
