# Generated by Django 5.1.7 on 2025-03-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('url_template', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'basemaps_wiroi_online',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBasemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_instances', to='basemaps.basemap')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basemaps', to='projects.project')),
            ],
            options={
                'db_table': 'project_basemaps_wiroi_online',
                'ordering': ['project', 'display_order'],
                'unique_together': {('project', 'basemap')},
            },
        ),
    ]
