# Generated by Django 5.1.7 on 2025-03-24 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemaps', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemap',
            options={'ordering': ['name'], 'verbose_name': 'Basemap', 'verbose_name_plural': 'Basemaps'},
        ),
        migrations.AlterModelOptions(
            name='projectbasemap',
            options={'ordering': ['project', 'display_order'], 'verbose_name': 'Project Basemap', 'verbose_name_plural': 'Project Basemaps'},
        ),
        migrations.AddField(
            model_name='basemap',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basemap',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basemap',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basemap',
            name='max_zoom',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='basemap',
            name='min_zoom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basemap',
            name='preview_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbasemap',
            name='custom_options',
            field=models.JSONField(blank=True, default=dict, help_text='Project-specific options that override the basemap defaults'),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='attribution',
            field=models.CharField(blank=True, help_text='Attribution text required by the map provider', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Additional options for the tile layer (e.g., subdomains, min/max zoom)'),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Maps'), ('google_satellite', 'Google Satellite'), ('openstreetmap', 'OpenStreetMap'), ('bing', 'Bing Maps'), ('esri', 'ESRI'), ('mapbox', 'Mapbox'), ('carto', 'Carto'), ('stamen', 'Stamen'), ('custom', 'Custom Tiles'), ('wms', 'WMS Service'), ('arcgis', 'ArcGIS Online'), ('blank', 'Blank Background')], default='openstreetmap', max_length=100),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='url_template',
            field=models.CharField(blank=True, help_text='URL template with {x}, {y}, {z} placeholders for tile coordinates', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectbasemap',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_basemaps', to='projects.project'),
        ),
    ]
