# Generated by Django 5.1.7 on 2025-03-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0003_remove_projectlayer_marker_library_name_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('function_type', models.CharField(max_length=50)),
                ('function_config', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'layer_functions_wiroi_online',
                'ordering': ['name'],
            },
        ),

        migrations.CreateModel(
            name='MapTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tool_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_options', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'map_tools_wiroi_online',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLayerFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_arguments', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layer_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_instances', to='functions.layerfunction')),
                ('project_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_functions', to='layers.projectlayer')),
            ],
            options={
                'db_table': 'project_layer_functions_wiroi_online',
                'unique_together': {('project_layer', 'layer_function')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('tool_options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='projects.project')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_instances', to='functions.maptool')),
            ],
            options={
                'db_table': 'project_tools_wiroi_online',
                'ordering': ['project', 'display_order'],
                'unique_together': {('project', 'tool')},
            },
        ),
    ]
