# Generated by Django 5.1.7 on 2025-03-24 17:56
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
        ('layers', '0003_remove_projectlayer_marker_library_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layerfunction',
            options={'ordering': ['name'], 'verbose_name': 'Layer Function', 'verbose_name_plural': 'Layer Functions'},
        ),
        migrations.AlterModelOptions(
            name='maptool',
            options={'ordering': ['name'], 'verbose_name': 'Map Tool', 'verbose_name_plural': 'Map Tools'},
        ),

        migrations.AlterModelOptions(
            name='projectlayerfunction',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name': 'Project Layer Function', 'verbose_name_plural': 'Project Layer Functions'},
        ),

        migrations.AlterModelOptions(
            name='projecttool',
            options={'ordering': ['project', 'display_order'], 'verbose_name': 'Project Tool', 'verbose_name_plural': 'Project Tools'},
        ),
        migrations.AddField(
            model_name='layerfunction',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layerfunction',
            name='function_code',
            field=models.TextField(blank=True, help_text='JavaScript code implementing the function', null=True),
        ),
        migrations.AddField(
            model_name='maptool',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maptool',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.AddField(
            model_name='maptool',
            name='tool_code',
            field=models.TextField(blank=True, help_text='JavaScript code implementing the tool', null=True),
        ),

        migrations.AddField(
            model_name='maptool',
            name='ui_position',
            field=models.CharField(choices=[('topright', 'Top Right'), ('topleft', 'Top Left'), ('bottomright', 'Bottom Right'), ('bottomleft', 'Bottom Left'), ('standalone', 'Standalone/Floating')], default='topright', max_length=50),
        ),

        migrations.AddField(
            model_name='projectlayerfunction',
            name='enabled',
            field=models.BooleanField(default=True),
        ),

        migrations.AddField(
            model_name='projectlayerfunction',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority for function execution order (higher = earlier)'),
        ),

        migrations.AddField(
            model_name='projecttool',
            name='custom_position',
            field=models.CharField(blank=True, help_text='Override the default UI position', max_length=50, null=True),
        ),

        migrations.AlterField(
            model_name='layerfunction',
            name='function_config',
            field=models.JSONField(blank=True, default=dict, help_text='Default configuration for the function'),
        ),

        migrations.AlterField(
            model_name='layerfunction',
            name='function_type',
            field=models.CharField(choices=[('clustering', 'Point Clustering'), ('filtering', 'Feature Filtering'), ('styling', 'Dynamic Styling'), ('analysis', 'Data Analysis'), ('labeling', 'Feature Labeling'), ('heatmap', 'Heat Map'), ('animation', 'Animation'), ('interaction', 'Custom Interaction'), ('format', 'Data Formatting'), ('transform', 'Geometry Transform')], default='clustering', max_length=50),
        ),

        migrations.AlterField(
            model_name='maptool',
            name='default_options',
            field=models.JSONField(blank=True, default=dict, help_text='Default options for the tool'),
        ),

        migrations.AlterField(
            model_name='maptool',
            name='tool_type',
            field=models.CharField(choices=[('measure_distance', 'Measure Distance'), ('measure_area', 'Measure Area'), ('draw_point', 'Draw Point'), ('draw_line', 'Draw Line'), ('draw_polygon', 'Draw Polygon'), ('export_data', 'Export Data'), ('print', 'Print Map'), ('search', 'Search Features'), ('select', 'Select Features'), ('edit', 'Edit Features'), ('custom', 'Custom Tool')], default='measure_distance', max_length=50),
        ),

        migrations.AlterField(
            model_name='projectlayerfunction',
            name='function_arguments',
            field=models.JSONField(blank=True, default=dict, help_text='Arguments specific to this function instance'),
        ),

        migrations.AlterField(
            model_name='projectlayerfunction',
            name='project_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='layers.projectlayer'),
        ),

        migrations.AlterField(
            model_name='projecttool',
            name='tool_options',
            field=models.JSONField(blank=True, default=dict, help_text='Project-specific tool options'),
        ),

    ]
